### PR TITLE
Susi adds Wireframes as per Card 2 in Waffle

### PR DESCRIPTION
**Pull request by susiirwin**
There are wireframes for Home Page, Item Show page, Log in Page and a Post-log-in page for the team's review and comments.

### CODE REVIEW

**Comment by PlanetEfficacy** [comment]
Nice work Susi. These wireframes look great.

**Comment by susiirwin** [comment]
Thanks Jesse!!! Glad you like them :) Excited to hear what David and Sonia think :)

**Comment by PlanetEfficacy** [comment]
K, I'll hold off until they check @tgisg @kctrlv

**Comment by tgisg** [comment]
@susiirwin Great job on the wireframes! 👍

**Comment by susiirwin** [comment]
Thanks @tgisg!!!

**Pull request merged**
